### ISSUE TITLE
Informar onde esta o rowspan.

### ISSUE THREAD

**Issue by marcobrunodev** [wbruno/gerador-emmkt#5]
Hoje quando temos um rowspan, o HTML não é parametrizado. Mas não é informado onde esta o rowspan, sendo assim, temos que abrir o código em um editor e depois voltar ao photoshop e corrigir o rowspan. O melhor seria se quando achar o rowspan informar onde esta para ir direto para o photoshop.

**Comment by wbruno** [comment]
Corrigido
